[project]
name = "bayes-error-paper"
version = "0.1.0"
description = "Code for the paper \"Practical estimation of the optimal classification error with soft labels and calibration\""
readme = "README.md"
authors = [
    { name = "RyotaUshio", email = "ushio@ms.k.u-tokyo.ac.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "bestperf",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
]

[tool.uv.sources]
bestperf = { workspace = true }
