[project]
name = "bayes-error-paper"
version = "0.1.0"
description = "Code for the paper \"Practical estimation of the optimal classification error with soft labels and calibration\""
readme = "README.md"
authors = [
    { name = "RyotaUshio", email = "ushio@ms.k.u-tokyo.ac.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "bestperf",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "openreview-py>=1.54.0",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "requests>=2.32.3",
    "scipy>=1.15.3",
    "tqdm>=4.67.1",
]

[tool.uv.sources]
bestperf = { workspace = true }
